# Generated by Django 4.2.7 on 2024-01-24 16:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорію',
                'verbose_name_plural': 'Категорії',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Картинка')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Ціна')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Знижка в %')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('wheel_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Розмір коліс')),
                ('frame', models.CharField(default='Стальна', max_length=100, verbose_name='Матеріал рами')),
                ('frame_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Розмір рами')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('series', models.CharField(max_length=100, verbose_name='Серія')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categories', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипеди',
                'db_table': 'product',
                'ordering': ('id',),
            },
        ),
    ]
