# Generated by Django 4.2.7 on 2024-01-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='frame',
            field=models.CharField(default='steel', max_length=100, verbose_name='Матеріал рами'),
        ),
    ]
